In [ ]:
#import de bibliotecas necessárias

import requests as req
import pandas as pd
from requests.exceptions import HTTPError

#definição de URL e caminho onde a tabela fato será salva

url = 'http://transparencia.al.gov.br/patrimonio/json-patrimonio-imobiliario/?limit=100&offset=0'
caminho_windows = r'C:\Users\Paulo\Desktop\Projeto N.H\fato.csv'

In [ ]:
#Requisição GET na API e transformação dos dados em DataFrame

requisicao = req.get(url)
try:

    requisicao.raise_for_status()

    dados = requisicao.json()
    df = pd.DataFrame(dados["rows"])
    print('Sucesso')

except HTTPError as htterr:
     print('Erro HTTP:', htterr)
except Exception as err:
     print('Erro normal', err)

Sucesso

In [ ]:
#Verificar sucesso da importação em outra célula para evitar requisições repetidas sem necessidade

df

,situacao_ocupacao,total_avaliacao,bairro,denominacao,afetacao,numero_dossie,municipio
0,OCUPADO,"141.148,37",CENTRO,7ª DELEGACIA REGIONAL DE POLÍCIA,,4208,DELMIRO GOUVEIA
1,OCUPADO,"4.800,00",RODOVIA AL 470,ÁREA DE TERRA,,5182,CHÃ PRETA
2,OCUPADO,"1.800,00",RODOVIA AL 470,ÁREA DE TERRA,,5183,CHÃ PRETA
3,OCUPADO,"4.100,00",RODOVIA AL 470,ÁREA DE TERRA,,5184,CHÃ PRETA
4,OCUPADO,"1.100,00",RODOVIA AL 470,ÁREA DE TERRA,,5185,CHÃ PRETA
...,...,...,...,...,...,...,...
95,OCUPADO,"5.715,15",POVOADO BAIXA DO MILHO,CAIXA DE QUEBRA DE PRESSÃO C.Q.P.,,4281,CANAPÍ
96,OCUPADO,"3.665.243,76",RODOVIA,CANAL DO SERTÃO,,5336,DELMIRO GOUVEIA
97,OCUPADO,"284.383,28",RODOVIA,CANAL DO SERTÃO,,5337,DELMIRO GOUVEIA
98,OCUPADO,"877.022,28",RODOVIA,CANAL DO SERTÃO,,5338,DELMIRO GOUVEIA
99,OCUPADO,"408.612,65",RODOVIA,CANAL DO SERTÃO,,5339,DELMIRO GOUVEIA

In [ ]:
#Salvando tabela fato

df.to_csv(r'C:\Users\Paulo\Desktop\Projeto N.H\fato.csv', index=False)

In [ ]:
#Lendo tabela fato para extrair dimensões

df_fato = pd.read_csv(caminho_windows)

In [ ]:
#Código GPT para verificação de duplicatas

df_fato[df_fato['numero_dossie'].duplicated(keep=False)] \
    .sort_values('numero_dossie')

Empty DataFrame
Columns: [situacao_ocupacao, total_avaliacao, bairro, denominacao, afetacao, numero_dossie, municipio]
Index: []

In [ ]:
#Código GPT para extração de dimensões da tabela fato

dim_municipio = df_fato[['municipio']].drop_duplicates().reset_index(drop=True)

dim_municipio['id_municipio'] = dim_municipio.index + 1

dim_municipio = dim_municipio[['id_municipio', 'municipio']]

df_fato = df_fato.merge(dim_municipio, on='municipio', how='left')

dim_municipio.to_csv(r'C:\Users\Paulo\Desktop\Projeto N.H\dimensoes\dim_municipio.csv')

In [ ]:
dim_situacao = df_fato[['situacao_ocupacao']].drop_duplicates().reset_index(drop=True)

dim_situacao['id_situacao'] = dim_situacao.index + 1

dim_situacao = dim_situacao[['id_situacao', 'situacao_ocupacao']]

df_fato = df_fato.merge(dim_situacao, on='situacao_ocupacao', how='left')

dim_situacao.to_csv(r'C:\Users\Paulo\Desktop\Projeto N.H\dimensoes\dim_situacao.csv')

In [9]:
dim_bairro = df_fato[['bairro']].drop_duplicates().reset_index(drop=True)

dim_bairro['id_bairro'] = dim_bairro.index + 1

dim_bairro = dim_bairro[['id_bairro', 'bairro']]

df_fato = df_fato.merge(dim_bairro, on='bairro', how='left')

dim_bairro.to_csv(r'C:\Users\Paulo\Desktop\Projeto N.H\dimensoes\dim_bairro.csv')

In [10]:
dim_denominacao = df_fato[['denominacao']].drop_duplicates().reset_index(drop=True)

dim_denominacao['id_denominacao'] = dim_denominacao.index + 1

dim_denominacao = dim_denominacao[['id_denominacao', 'denominacao']]

df_fato = df_fato.merge(dim_denominacao, on='denominacao', how='left')

dim_denominacao.to_csv(r'C:\Users\Paulo\Desktop\Projeto N.H\dimensoes\dim_denominacao.csv')